# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-04 12:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20170312_0128'),
    ]

    operations = [
        migrations.RunSQL(
            ('CREATE FULLTEXT INDEX post_search ON blog_post (title, body)',)
        )
    ]
